

name: 📦 Make linux release

on: 
  workflow_call:
    inputs:
      tdSha:
        required: false
        type: string
    secrets:
      uploadUrl:
        required: true
      GH_TOKEN:
        required: true

jobs:
  linux-Build:
    name: Build on Ubuntu ${{ matrix.osVersion }}
    strategy:
      matrix:
        include:
        - clang: 14
          os: ubuntu-22.04
          osVersion: 22.04
        - clang: 10
          os: ubuntu-20.04
          osVersion: 20.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tdLib repo
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.tdSha }}
          repository: tdlib/td
          
      - name: Install packages from apt
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: make git zlib1g-dev libssl-dev gperf php-cli cmake clang-${{ matrix.clang }} libc++-dev libc++abi-dev
          version: 1.0-${{ matrix.osVersion }}
      
      - name: Disable Test, Benchmark and other not used projects build
        run: |
          cmakelists_content=$(cat CMakeLists.txt)
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/add_subdirectory(test)/# add_subdirectory(test)/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/add_subdirectory(benchmark)/# add_subdirectory(benchmark)/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/add_executable(tg_cli td\/telegram\/cli.cpp ${TL_TD_JSON_SOURCE})/# add_executable(tg_cli td\/telegram\/cli.cpp ${TL_TD_JSON_SOURCE})/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/target_link_libraries(tg_cli PRIVATE ${READLINE_LIBRARY})/# target_link_libraries(tg_cli PRIVATE ${READLINE_LIBRARY})/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/target_include_directories(tg_cli SYSTEM PRIVATE ${READLINE_INCLUDE_DIR})/# target_include_directories(tg_cli SYSTEM PRIVATE ${READLINE_INCLUDE_DIR})/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/target_compile_definitions(tg_cli PRIVATE -DUSE_READLINE=1)/# target_compile_definitions(tg_cli PRIVATE -DUSE_READLINE=1)/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/target_link_libraries(tg_cli PRIVATE memprof tdclient tdcore)/# target_link_libraries(tg_cli PRIVATE memprof tdclient tdcore)/')
          cmakelists_content=$(echo "$cmakelists_content" | sed 's/add_dependencies(tg_cli tl_generate_json)/# add_dependencies(tg_cli tl_generate_json)/')
          echo "$cmakelists_content" > CMakeLists.txt

          cmakelists_tdactor_content=$(cat ./tdactor/CMakeLists.txt)
          cmakelists_tdactor_content=$(echo "$cmakelists_tdactor_content" | sed 's/add_executable(example example\/example.cpp)/# add_executable(example example\/example.cpp)/')
          cmakelists_tdactor_content=$(echo "$cmakelists_tdactor_content" | sed 's/target_link_libraries(example PRIVATE tdactor)/# target_link_libraries(example PRIVATE tdactor)/')
          echo "$cmakelists_tdactor_content" > ./tdactor/CMakeLists.txt
  
          cmakelists_tddb_content=$(cat ./tddb/CMakeLists.txt)
          cmakelists_tddb_content=$(echo "$cmakelists_tddb_content" | sed 's/add_executable(binlog_dump td\/db\/binlog\/binlog_dump.cpp)/# add_executable(binlog_dump td\/db\/binlog\/binlog_dump.cpp)/')
          cmakelists_tddb_content=$(echo "$cmakelists_tddb_content" | sed 's/target_link_libraries(binlog_dump PRIVATE tddb)/# target_link_libraries(binlog_dump PRIVATE tddb)/')
          echo "$cmakelists_tddb_content" > ./tddb/CMakeLists.txt

      - name: Configure
        env:
          CC: /usr/bin/clang-${{ matrix.clang }}
          CXX: /usr/bin/clang++-${{ matrix.clang }}
          CXXFLAGS: -stdlib=libc++
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..

      - name: Build
        env:
          CC: /usr/bin/clang-${{ matrix.clang }}
          CXX: /usr/bin/clang++-${{ matrix.clang }}
          CXXFLAGS: -stdlib=libc++
        working-directory: ./build
        run: |
          cmake --build . --target install -j 2

      - name: Copy files
        working-directory: ./build
        run: |
          mkdir ../binaryR
          cp ../td/generate/scheme/td_api.tl ../binaryR
          cp libtdjson.so ../binaryR
          cp /usr/lib/x86_64-linux-gnu/libcrypto.so ../binaryR
          cp /usr/lib/x86_64-linux-gnu/libssl.so ../binaryR
          cp /usr/lib/x86_64-linux-gnu/libz.so ../binaryR

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          retention-days: 5
          name: TDLib-x64-ubuntu-${{ matrix.osVersion }}
          path: binaryR

      - name: Make zip file
        run: zip -j TDLib-x64-ubuntu-${{ matrix.osVersion }}.zip binaryR/*

      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ secrets.uploadUrl }}
          asset_name: TDLib-x64-ubuntu-${{ matrix.osVersion }}.zip
          asset_path: ${{ github.workspace }}/TDLib-x64-ubuntu-${{ matrix.osVersion }}.zip
          asset_content_type: application/octet-stream
