name: 📦 Make Windows release

on: 
  workflow_call:
    inputs:
      tdSha:
        required: false
        type: string
    secrets:
      uploadUrl:
        required: true
      GH_TOKEN:
        required: true

jobs:
  macOS-Build:
    name: Build on Windows ${{ matrix.osVersion }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2022
          osVersion: 2022
        - os: windows-2019
          osVersion: 2019

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tdLib repo
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ inputs.tdSha }}
          repository: tdlib/td

      - name: Cache vcpkg
        uses: actions/cache@v3.3.2
        id: cache
        with:
          path: vcpkg
          key: vcpkg-windows-${{ matrix.os }}
          restore-keys: vcpkg-windows-${{ matrix.os }}

      - name: Checkout vcpkg repo
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.0.0
        with:
          ref: 1b1ae50e1a69f7c659bd7d731e80b358d21c86ad
          repository: Microsoft/vcpkg
          path: vcpkg

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
         cd vcpkg
         ./bootstrap-vcpkg.bat -disableMetrics
         ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows readline:x64-windows

      - name: Configure
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..

      - name: Configure & Build
        shell: cmd
        working-directory: ./build
        run: |
          cmake --build . --target install --config Release -j 1

      - name: Copy files
        run: |
          mkdir binaryR
          copy td\generate\scheme\td_api.tl binaryR
          copy tdlib\bin\libcrypto-1_1-x64.dll binaryR
          copy tdlib\bin\libssl-1_1-x64.dll binaryR
          copy tdlib\bin\tdjson.dll binaryR
          copy tdlib\bin\zlib1.dll binaryR

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          retention-days: 5
          name: TDLib-x64-Windows-${{ matrix.osVersion }}
          path: binaryR

      - name: Make zip file
        shell: cmd
        run: |
          cd binaryR
          7z a ../TDLib-x64-Windows-${{ matrix.osVersion }}.zip *

      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ secrets.uploadUrl }}
          asset_name: TDLib-x64-Windows-${{ matrix.osVersion }}.zip
          asset_path: ${{ github.workspace }}/TDLib-x64-Windows-${{ matrix.osVersion }}.zip
          asset_content_type: application/octet-stream
